# -*- coding: utf-8 -*-
"""CustomerSegmentation_Using_Kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oWdLiTf379OAeNRc7aRb57Ih2gS3s8-G

Importing and Dependies
"""

import pandas as pd
import numpy as ny
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA

"""Data collection and analysis"""

customer_data= pd.read_csv('/content/Mall_Customers.csv')

customer_data.head()

customer_data.shape

customer_data.info()

customer_data.isnull().sum()

"""Choosing the Annual Income Column and Spending column

"""

X = [['Annual Income (k$)', 'Spending Score (1-100)']]

X=customer_data.iloc[:,[3,4]].values

print(X)

"""Choosing the correct number of Clusters


WCSS>> Within Clusters Sum of Square
"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

wcss= []
for i in range(1,11):
  kmeans=KMeans(n_clusters=i, init='k-means++', random_state=42)
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)
plt.plot(range(1,11), wcss, marker='o')
sns.set_style('darkgrid')
plt.plot(range(1,11),wcss)
plt.title('The Elbow Graph')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()
plt.show()

"""Optimium No. KMeans Clustering = 5


Training the kmeans Clustering Model
"""

kmeans= KMeans(n_clusters=5, init='k-means++',random_state=0)

Y=kmeans.fit_predict(X)
print(Y)

"""Silhouette Score"""

score = silhouette_score(X_scaled, Y)
print(score)

"""Visualizing all the Clusters


Five Clusters 0,1,2,3,4
"""

plt.figure(figsize=(8,8))
plt.scatter(X[Y==0,0],X[Y==0,1],s=50,c='green',label='Cluster 1')
plt.scatter(X[Y==1,0],X[Y==1,1],s=50,c='red',label='Cluster 2')
plt.scatter(X[Y==2,0],X[Y==2,1],s=50,c='yellow',label='Cluster 3')
plt.scatter(X[Y==3,0],X[Y==3,1],s=50,c='pink',label='Cluster 4')
plt.scatter(X[Y==4,0],X[Y==4,1],s=50,c='blue',label='Cluster 5')

plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=100,c='black',label='Centroids')
plt.title('Customer Groups')
plt.xlabel('Annual Income')
plt.ylabel('Spending Score')
plt.show()

plt.figure(figsize=(10, 8))
plt.scatter(X[:, 0], X[:, 1], c=Y, cmap='viridis', s=100, label='Customers')
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s=200, c='red', marker='X', label='Centroids')
plt.title('Customer Groups (KMeans Clustering)')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.show()

"""PCA"""

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.scatter(X_pca[:,0], X_pca[:,1], c=Y, cmap='viridis')
plt.title('PCA of Customer Segments')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.show()

customer_data['Cluster'] = Y
customer_data.groupby('Cluster')[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']].mean()